# Generated by Django 3.1 on 2020-08-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stan1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_value', models.CharField(max_length=30)),
                ('level_value', models.CharField(max_length=10)),
                ('temp_value', models.CharField(max_length=10)),
                ('package_value', models.IntegerField(default=0)),
                ('power', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stan2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_value', models.CharField(max_length=30)),
                ('level_value', models.CharField(max_length=10)),
                ('temp_value', models.CharField(max_length=10)),
                ('package_value', models.IntegerField(default=0)),
                ('power', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stan3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_value', models.CharField(max_length=30)),
                ('level_value', models.CharField(max_length=10)),
                ('temp_value', models.CharField(max_length=10)),
                ('package_value', models.IntegerField(default=0)),
                ('power', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stan4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_value', models.CharField(max_length=30)),
                ('level_value', models.CharField(max_length=10)),
                ('temp_value', models.CharField(max_length=10)),
                ('package_value', models.IntegerField(default=0)),
                ('power', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
