# Generated by Django 3.1 on 2020-08-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0002_auto_20200818_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stan1',
            name='level_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stan2',
            name='level_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stan3',
            name='level_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stan4',
            name='level_value',
            field=models.FloatField(default=0),
        ),
    ]
