# Generated by Django 3.1 on 2020-08-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stan1',
            name='date_value',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='stan2',
            name='date_value',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='stan3',
            name='date_value',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='stan4',
            name='date_value',
            field=models.DateTimeField(),
        ),
    ]
