# Generated by Django 3.1 on 2020-08-20 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0003_auto_20200819_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stan1',
            old_name='power',
            new_name='power_value',
        ),
        migrations.RenameField(
            model_name='stan2',
            old_name='power',
            new_name='power_value',
        ),
        migrations.RenameField(
            model_name='stan3',
            old_name='power',
            new_name='power_value',
        ),
        migrations.RenameField(
            model_name='stan4',
            old_name='power',
            new_name='power_value',
        ),
    ]
